### ISSUE TITLE
pretrained load error

### ISSUE THREAD

**Issue by YinengXiong** [sharif-apu/LDR2HDR_NTIRE21#2]
RuntimeError: Error(s) in loading state_dict for ResMKHDR:
        Unexpected key(s) in state_dict: "attention1.fc.0.weight", "attention1.fc.2.weight", "noiseGate1.weight", "noiseGate1.bias", "noiseGate2.weight", "noiseGate2.bias", "attention2.fc.0.weight", "attention2.fc.2.weight".

**Comment by sharif-apu** [comment]
Please check the updated code. I hope it has been fixed.

**Comment by sharif-apu** [comment]
> Please check the updated code. I hope it has been f
