### ISSUE TITLE
pretrained model seems get poor PSNR and mu-PSNR

### ISSUE THREAD

**Issue by YinengXiong** [sharif-apu/LDR2HDR_NTIRE21#3]
hello,
I use your pretrained model to inference on 100 images random selected from the train set of NTIRE 2021 HDR challenge, and got <0 PSNR and about ~5dB mu-PSNR score

**Comment by sharif-apu** [comment]
Can you please tell me which exposure setting you are using? According to the challenge protocol, the model was trained with medium exposure images only.

**Comment by sharif-apu** [comment]
![sampleTestingOutput(8-Bit)](https://user-images.githubusercontent.com/15001857/116899646-a37ee000-ac59-11eb-9083-7d601914ed31.png)
![sampleTestingOutput(16-Bit)](https://user-images.githubusercontent.com/15001857/116899659-a679d080-ac59-11eb-939a-f75c3bfe43c8.png) 

I've cross-checked the output with the pretrained weights. It seems to be fine. Please have a look at the sample outputs. Please check your input images.

**Comment by sharif-apu** [comment]
I've cross-checked the output with the pretrained weights. It seems to be fine. Please have a look at the sample outputs. Please check your input images.
![Uploading 0028.png…]()

**Comment by sharif-apu** [comment]
I've cross-checked the output with the pretrained weights. It seems to be fine. For your reference, I've added sample outputs in the modelOutput/ directory. . Please check your input images.

**Comment by YinengXiong** [comment]
> I've cross-checked the output with the pretrained weights. It seems to be fine. For your reference, I've added sample outputs in the modelOutput/ directory. . Please check your input images.

Hi ! 
I use the images in `modelOutput/Two-stageHDR/HDRInput/` and the provided pretrained model to generate output, and I got
`0028_alignratio.npy`  
>>> np.load('./testOutTwo-stageHDR/0028/0028_alignratio.npy').astype(np.float32)
array(19877.906, dtype=float32)
while in your provided output, 
>>> np.load('./modelOutput/Two-stageHDR/HDRInput/0028_alignratio.npy').astype(np.float32)
array(21488.842, dtype=float32)

I didn't change any code

**Comment by sharif-apu** [comment]
Hello!
xxx_alignration.py is metadata for normalizing 16-bit images. Notably, the input of our model is 8-bit images and any 16bit-samples/.npy files have to be ignored while reading data input images. 

The samples we have provided in the "modelOutput/" directory are saved according to the NTIRE-21 submission protocol. Ideally, these samples should not be used for the inference. I will strongly suggest you to go through the following link: https://competitions.codalab.org/competitions/28161. You may also download the testing samples from the given link as well (after registration). It is worth noting, the output of our Model is stored in 16-bit format, which is the range between (0-65536). Therefore, we may not treat them as normal images. Please refer to the original paper and the competition link for the details. Also, for calculating PSNR and mu-PSNR we should use the script provided by the organizer of the competition. However, for any difficulties feel free to contact us.
