### ISSUE TITLE
the dataset can not be download

### ISSUE THREAD

**Issue by qinhaifangpku** [sharif-apu/LDR2HDR_NTIRE21#4]
hi, It is very appreciate for your fancy work!

Now I am working in this task while the dataset in the link you provided was not worked for me:

I registered in the competition page and get the information below:

"Your request to participate in this challenge has been received and a decision is pending."

Do you have any suggestions about next step?

**Comment by sharif-apu** [comment]
Hi There!
As you already pointed out, all rights of the dataset are reserved by the competition authority. Therefore, we may not help you in collecting the dataset.  However, you may send an email to the organizer for providing you with the dataset. In the worst case, you may train the model with other existing HDR datasets.
